### ISSUE TITLE
aarch64-apple-darwin

### ISSUE THREAD

**Issue by TomLiu-GitHub** [lbl8603/switch#10]
在今年 WWDC23 上，最后一款使用英特尔芯片的 Mac Pro 产品转变搭载 M2 Ultra 芯片，虽然比设想中的要迟了一年，但苹果依然是彻底告别了英特尔芯片时代。
只有历史版本的mac机器使用x86_64-apple-darwin架构
新机器将是aarch64-apple-darwin架构

能帮我Releases一个aarch64-apple-darwin吗

**Comment by uk0** [comment]
我可以提交一个 你试试 需要等待合并

**Comment by TomLiu-GitHub** [comment]
[switch-cmd-aarch64-apple-darwin-1.1.0.zip](https://github.com/lbl8603/switch/files/12114834/switch-cmd-aarch64-apple-darwin-1.1.0.zip)
