### ISSUE TITLE
(The service is not installed and started in the current process

### ISSUE THREAD

**Issue by hshe** [lbl8603/switch#3]
![image](https://user-images.githubusercontent.com/8075773/229488554-ea38b634-9c9e-4aa1-a359-cd6485bcacf7.png)

**Comment by lbl8603** [comment]
On Windows, you can choose to install services.
![图片](https://user-images.githubusercontent.com/49143209/230025565-c0390e7c-3583-4697-bf97-f4e9c6c75b1a.png)
