### ISSUE TITLE
win10是否可以运行

### ISSUE THREAD

**Issue by zy1818** [lbl8603/switch#4]
win10是否可以运行？看着帮助没玩起来，能不能出个简单的操作流程

**Comment by lbl8603** [comment]
运行报错吗，我自己的win10是能运行的，你可以尝试下自己编译

**Comment by lbl8603** [comment]
在windows上，需要下载 wintun.dll(https://www.wintun.net/)，和switch.exe放到同级目录下

**Comment by zy1818** [comment]
wintun我加了，卸载服务改了一下目录就再也装不了服务了

**Comment by lbl8603** [comment]
报错信息呢

**Comment by zy1818** [comment]
他不报错啊

**Comment by zy1818** [comment]
C:\Users\zy1818\Desktop\switch>switch.exe install --path C:\Users\zy1818\Desktop\switch
thread 'main' panicked at 'Os { code: 32, kind: Uncategorized, message: "另一个程序正在使用此文件，进程无法访问。" }', switch-desktop\src\windows\mod.rs:251:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lbl8603** [comment]
换个空的安装目录

**Comment by zy1818** [comment]
D:\switch>switch.exe install --path D:\switch
thread 'main' panicked at 'Os { code: 32, kind: Uncategorized, message: "另一个程序正在使用此文件，进程无法访问。" }', switch-desktop\src\windows\mod.rs:251:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zy1818** [comment]
换完也是一样

**Comment by lbl8603** [comment]
我这重现不了你的问题，要不重启电脑试一下

**Comment by zy1818** [comment]
重启也不行

**Comment by zy1818** [comment]
搞个QQ群吧，让更多的人参与进来

**Comment by lbl8603** [comment]
加我qq吧 1791778604

**Comment by lbl8603** [comment]
不对啊，看你安装的命令有问题   要用个空目录，比如'D:\switch>switch.exe install --path D:\switch\bin'

**Comment by zy1818** [comment]
等一下测试

**Comment by zy1818** [comment]
QQ不对吧

**Comment by zy1818** [comment]
我QQ109073041
