### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by steom** [lbl8603/switch#7]
Please consider to run the Windows binary without the need to install service.

**Comment by lbl8603** [comment]
You can run it directly without installing the service

**Comment by steom** [comment]
no, the switch-desktop.exe start don't work without the service installed

**Comment by lbl8603** [comment]
Please describe the specific problem.

**Comment by steom** [comment]
switch-desktop.exe only control the daemon switch-service-v1.exe

the switch-desktop.exe "start" don't work without the service switch-service-v1.exe installed and running

switch-desktop.exe "start" only create the (unneeded) config file for the service.

**Comment by lbl8603** [comment]
Is there any abnormal information?

**Comment by steom** [comment]
The service is not installed and started in the current process
![image](https://github.com/lbl8603/switch/assets/5721593/e2d4dcf5-ae44-499c-b311-27fab4547fe3)

**Comment by lbl8603** [comment]
This is just a reminder and does not affect normal use

**Comment by lbl8603** [comment]
![图片](https://github.com/lbl8603/switch/assets/49143209/748b8d8b-90d5-406d-a287-de0beed97bb8)

Example of a successful start

**Comment by steom** [comment]
ok, with the service present but not started don't work...
i've deleted the service, now start.
